version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
    groups:
      development:
        dependency-type: 'development'
        patterns:
          - '**'
      production:
        dependency-type: 'production'
        patterns:
          - '**'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
