name: PR

on: [pull_request]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  # See: https://github.com/vercel/turborepo/issues/9320#issuecomment-2499219314
  TURBO_SCM_BASE: ${{ github.event.pull_request.base.sha }}

jobs:
  # This job should watrm warm up the caches.
  install-deps:
    name: Checkout and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install

  lint-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install
        with:
          cache-name: lint

      - name: Run Lint
        run: pnpm lint --force

      - name: Run Format Check
        run: pnpm format:check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install
        with:
          cache-name: test

      - name: Install Playwright Browsers
        run: pnpm exec playwright install

      - name: Run Tests
        run: pnpm test --force

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install
        with:
          cache-name: build

      - name: Run Build
        run: pnpm build --force

  packages-versions:
    name: Check Packages Versions
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install

      - name: Run Packages Versions Check
        run: pnpm lint:versions

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install

      - name: Run Spell Check
        run: pnpm lint:spell

  unused:
    name: Check Unused Code
    runs-on: ubuntu-latest
    needs: [install-deps]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - name: Install Dependencies
        uses: ./.github/actions/prepare-install

      - name: Run Unused Code Check
        run: pnpm lint:unused
